site_name: "callingCardsTools Documentation"
site_description: "A collection of objects and functions to work with calling cards sequencing tools"
site_author: "Chase Mateusiak"
site_url: "https://cmatkhan.github.io/callingCardsTools/"
repo_url: "https://github.com/cmatKhan/callingCardsTools"
repo_name: "callingCardsTools"
edit_uri: "edit/master/docs/"
watch: ['callingcardstools', 'docs']

theme:
  name: material

plugins:
- search
- autorefs
- section-index
- mkdocstrings:
    handlers:
          python:
            paths: [callingCardsTools]  # search packages in the src folder
            docstring_style: 'google'
            merge_init_into_class: True

nav:
- Home:
  - Overview: index.md
  - Changelog: home/changelog.md
  - Contributing: home/contributing.md
  - License: home/license.md
- "File Format Specs":
  - barcode_details: "file_format_specs/barcode_details.md"
  - qBed: "file_format_specs/qbed.md"
  - yeast_rank_response: "file_format_specs/yeast_rank_response.md"
- API:
  - Alignment:
    - AlignmentTagger: 'API/Alignment/AlignmentTagger.md'
    - SummaryParser: 'API/Alignment/SummaryParser.md'
    - mammals:
      - Qbed: 'API/Alignment/mammals/Qbed.md'
  - Analysis:
    - yeast:
      - read_in_data:
        - read_in_data: 'API/Analysis/yeast/read_in_data/read_in_data.md'
        - combine_data: 'API/Analysis/yeast/read_in_data/combine_data.md'
      - rank_response:
        - bin_by_binding_rank: 'API/Analysis/yeast/rank_response/bin_by_binding_rank.md'
        - compute_rank_response: 'API/Analysis/yeast/rank_response/compute_rank_response.md'
        - create_partitions: 'API/Analysis/yeast/rank_response/create_partitions.md'
        - create_rank_response_table: 'API/Analysis/yeast/rank_response/create_rank_response_table.md'
        - label_responsive_genes: 'API/Analysis/yeast/rank_response/label_responsive_genes.md'
        - parse_binomtest_results: 'API/Analysis/yeast/rank_response/parse_binomtest_results.md'
        - validate_config: 'API/Analysis/yeast/rank_response/validate_config.md'
      - find_min_responsive:
        - find_min_responsive: 'API/Analysis/yeast/find_min_responsive/find_min_responsive.md'
      - chipexo_promoter_sig:
        - read_in_chipexo_data: 'API/Analysis/yeast/chipexo_promoter_sig/read_in_chipexo_data.md'
        - chipexo_promoter_sig: 'API/Analysis/yeast/chipexo_promoter_sig/chipexo_promoter_sig.md'
  - BarcodeParser:
    - mammals:
      - BarcodeCounterQc: 'API/BarcodeParser/mammals/BarcodeCounterQc.md'
    - yeast:
      - BarcodeCounterQc: 'API/BarcodeParser/yeast/BarcodeCounterQc.md'
  - PeakCalling:
    - yeast:
      - read_in_data:
        - qbed_df_to_pyranges: "API/PeakCalling/yeast/read_in_data/qbed_df_to_pyranges.md"
        - read_in_background_data: "API/PeakCalling/yeast/read_in_data/read_in_background_data.md"
        - read_in_chrmap: "API/PeakCalling/yeast/read_in_data/read_in_chrmap.md"
        - read_in_experiment_data: "API/PeakCalling/yeast/read_in_data/read_in_experiment_data.md"
        - read_in_promoter_data: "API/PeakCalling/yeast/read_in_data/read_in_promoter_data.md"
        - relabel_chr_column: "API/PeakCalling/yeast/read_in_data/relabel_chr_column.md"
      - enrichment_vectorized: "API/PeakCalling/yeast/enrichment_vectorized.md"
      - hypergeom_pval_vectorized: "API/PeakCalling/yeast/hypergeom_pval_vectorized.md"
      - poisson_pval_vectorized: "API/PeakCalling/yeast/poisson_pval_vectorized.md"
      - call_peaks:
        - count_hops: 'API/PeakCalling/yeast/call_peaks/count_hops.md'
        - add_metrics: 'API/PeakCalling/yeast/call_peaks/add_metrics.md'
        - call_peaks: 'API/PeakCalling/yeast/call_peaks/call_peaks.md'
        - parse_args: 'API/PeakCalling/yeast/call_peaks/parse_args.md'
        - main: 'API/PeakCalling/yeast/call_peaks/main.md'
  - QC:
    - create_status_coder: 'API/QC/create_status_coder.md'
    - StatusFlags: 'API/QC/StatusFlags.md'
  - Reads:
    - ReadParser: 'API/Reads/ReadParser.md'
  - Resources:
    - Resources: 'API/Resources/Resources.md'

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists