site_name: "callingCardsTools Documentation"
site_description: "A collection of objects and functions to work with calling cards sequencing tools"
site_author: "Chase Mateusiak"
site_url: "https://cmatkhan.github.io/callingCardsTools/"
repo_url: "https://github.com/cmatKhan/callingCardsTools"
repo_name: "callingCardsTools"
edit_uri: "edit/master/docs/"
watch: ['src']

theme:
  name: material

plugins:
- search
- autorefs
- section-index
- mkdocstrings:
    handlers:
          python:
            paths: [src]  # search packages in the src folder
            docstring_style: 'google'
            merge_init_into_class: True

nav:
- Home:
  - Overview: index.md
  - Changelog: home/changelog.md
  - License: home/license.md
- "File Format Specs":
  - barcode_details: "file_format_specs/barcode_details.md"
  - qBed: "file_format_specs/qbed.md"
- API:
  - Alignment:
    - AlignmentTagger: 'API/Alignment/AlignmentTagger.md'
    - SummaryParser: 'API/Alignment/SummaryParser.md'
    - mammals:
      - Qbed: 'API/Alignment/mammals/Qbed.md'
  - BarcodeParser:
    - mammals:
      - BarcodeCounterQc: 'API/BarcodeParser/mammals/BarcodeCounterQc.md'
    - yeast:
      - BarcodeCounterQc: 'API/BarcodeParser/yeast/BarcodeCounterQc.md'
  - QC:
    - create_status_coder: 'API/QC/create_status_coder.md'
    - StatusFlags: 'API/QC/StatusFlags.md'
  - Reads:
    - ReadParser: 'API/Reads/ReadParser.md'
  - Resources:
    - Resources: 'API/Resources/Resources.md'
- "Testing, Debugging and Contributing":
  - Reproducible Debugging: 'testing_debugging_contributing/Reproducible_Debugging.md'

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists