contact_links:
  - name: Get help and talk to each other
    url: https://github.com/cmatKhan/callingcardstools/discussions
    about: This is a message board intended for individual help and discussion about the callnigcardstools package
