version: 1 
formatters: 
   default: 
      format: '%(asctime)s [%(levelname)s] %(name)s.%(funcName)s:%(lineno)d:%(message)s' 

handlers:
  console_handler:
    class: logging.StreamHandler
    level: WARNING
    formatter: default

  file_handler:
    class: logging.FileHandler
    level: INFO
    filename: callingcardstools.log
    formatter: default

root: 
    level: ERROR 
    handlers: [console_handler,file_handler]
    propogate: true
